mutation addServiceSource($input: AddServiceSourceInput!) {
  addServiceSource(input: $input)
}

mutation addRelation($input: AddRelationInput!) {
  addRelation(input: $input)
}

query getImage($id: ID!) {
  image(id: $id) {
    id
    name
    url
  }
}
